### ISSUE TITLE
`smtplib.SMTPSenderRefused` Error while Sending Mail using API

### ISSUE THREAD

**Issue by ZenithClown** [pOrgz-dev/mailer#8]
**Description:** API is connected and Flask Application is running as expected, yet the email is not sent; the error traceback is attached below. Currently, the API is available at `{{URI}}/api/v1/mailer`.

```python
Traceback (most recent call last):
  File "D:\Anaconda3\Lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "D:\Anaconda3\Lib\site-packages\flask\app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\debma\AppData\Roaming\Python\Python38\site-packages\flask_restful\__init__.py", line 272, in error_router
    return original_handler(e)
  File "D:\Anaconda3\Lib\site-packages\flask\app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Anaconda3\Lib\site-packages\flask\_compat.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "D:\Anaconda3\Lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Anaconda3\Lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\debma\AppData\Roaming\Python\Python38\site-packages\flask_restful\__init__.py", line 272, in error_router
    return original_handler(e)
  File "D:\Anaconda3\Lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Anaconda3\Lib\site-packages\flask\_compat.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "D:\Anaconda3\Lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Anaconda3\Lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\debma\AppData\Roaming\Python\Python38\site-packages\flask_restful\__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "D:\Anaconda3\Lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\debma\AppData\Roaming\Python\Python38\site-packages\flask_restful\__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "E:\pOrgz-dev\mailer\app\main\controller\main.py", line 35, in get
    self.mailer.sendMail(
  File "E:\pOrgz-dev\mailer\app\main\controller\_base_mailer.py", line 88, in sendMail
    self.mail_server.send_message(email_message)
  File "D:\Anaconda3\Lib\smtplib.py", line 970, in send_message
    return self.sendmail(from_addr, to_addrs, flatmsg, mail_options,
  File "D:\Anaconda3\Lib\smtplib.py", line 871, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (501, b'<email-address> size=205: malformed address: size=205 may not follow <email-address>', 'email-address')
```

- [ ] is the mailing application running in standalone mode?
- [ ] are all `args` parsed correctly?
- [ ] are the `args` type correctly parsed?
- [ ] does flask requires special permission while running from `localhost` and from `server`?
- [ ] check if `flask-mail` is feasible and responsive as opposed to `email`

**Comment by ZenithClown** [comment]
On 90fcbf3 received same error (given below). Thus, **failing to run on standalone mode**.

```console
PS E:\pOrgz-dev\mailer\app\test> python .\dry_run.py
INFO : Import Succesful.
Checking for: _base_mailer: PROTOCOL = SMTP
MMail Not Sent. Received - <<class 'smtplib.SMTPSenderRefused'> - (501, b'<email-address> size=264: malformed address: size=264 may not follow <email-address>', 'email-address')>
MMail Not Sent. Received - <<class 'smtplib.SMTPSenderRefused'> - (501, b'<email-address> size=560: malformed address: size=560 may not follow <email-address>', 'email-address')>
```
